apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: vacm-hub1-node1
    kubevirt.io/dynamic-credentials-support: 'true'
    vm.kubevirt.io/template: fedora-server-small
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.32.2
  name: vacm-hub1-node1
  namespace: vacm-hub1
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
        creationTimestamp: null
        name: vacm-hub1-node1
      spec:
        source:
          blank: {}
        storage:
          resources:
            requests:
              storage: 120Gi
    - metadata:
        creationTimestamp: null
        name: vacm-hub1-node1-installation-cdrom
      spec:
        source:
          http:
            url: 'http://192.168.58.15/iso/vacm1.iso'
        storage:
          resources:
            requests:
              storage: 5Gi
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: coreos
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: vacm-hub1-node1
        kubevirt.io/size: small
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 2
              disk:
                bus: virtio
              name: rootdisk
            - bootOrder: 3
              disk:
                bus: virtio
              name: cloudinitdisk
            - bootOrder: 1
              cdrom:
                bus: sata
              name: installation-cdrom
          interfaces:
            - bridge: {}
              macAddress: 'de:ad:be:ee:20:00'
              model: virtio
              name: nic-salmon-hippopotamus-14
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 2Gi
        resources: {}
      networks:
        - multus:
            networkName: localnet-network
          name: nic-salmon-hippopotamus-14
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: vacm-hub1-node1
          name: rootdisk
        - dataVolume:
            name: vacm-hub1-node1-installation-cdrom
          name: installation-cdrom
        - cloudInitNoCloud:
            networkData: |
              ethernets:
                enp1s0:
                  addresses:
                    - 192.168.58.110
                  gateway4: 192.168.58.1
              version: 2
            userData: |-
              #cloud-config
              user: fedora
              password: o1hc-rg3h-rdoq
              chpasswd: { expire: False }
          name: cloudinitdisk
