apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: master1
  name: master1
  namespace: vacm-hub1
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        kubevirt.io/domain: master1
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 8
          sockets: 1
          threads: 2
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
          interfaces:
            - bridge: { }
              macAddress: de:ad:be:ff:20:00
              model: virtio
              name: enp1s0
        memory:
          guest: 16Gi
      networks:
        - multus:
            networkName: localnet-network
          name: enp1s0
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: master1-rootdisk
          name: rootdisk
        - cloudInitNoCloud:
            networkData: |
              ethernets:
                enp1s0:
                  addresses:
                    - 192.168.58.51
                  gateway4: 192.168.58.1
              version: 2
          name: cloudinitdisk


