apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: master2.vacm1.outbound.vz.bos2.lab
  name: master2.vacm1.outbound.vz.bos2.lab
  namespace: vacm-hub1
spec:
  template:
    metadata:
      labels:
        kubevirt.io/domain: master2.vacm1.outbound.vz.bos2.lab
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 8
          sockets: 1
          threads: 2
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
          interfaces:
            - bridge: {}
              macAddress: de:ad:be:ff:20:10
              model: virtio
              name: enp1s0
        memory:
          guest: 16Gi
      networks:
        - multus:
            networkName: localnet-network
          name: enp1s0
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: master2-rootdisk
          name: rootdisk
        - dataVolume:
            name: master2-cdrom
          name: cdrom
        - cloudInitNoCloud:
            networkData: |
              ethernets:
                enp1s0:
                  addresses:
                    - 192.168.58.52
                  gateway4: 192.168.58.1
              version: 2
          name: cloudinitdisk

