apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: sno1.outbound.vz.bos2.lab
  name: sno1.outbound.vz.bos2.lab
  namespace: sno-clusters
spec:
  runStrategy: RerunOnFailure
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
        creationTimestamp: null
        name: sno1-rootdisk
      spec:
        source:
          blank: {}
        storage:
          resources:
            requests:
              storage: 120Gi
  template:
    metadata:
      labels:
        kubevirt.io/domain: sno1.outbound.vz.bos2.lab
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 8
          sockets: 1
          threads: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          interfaces:
          - bridge: {}
            macAddress: de:ad:be:ff:20:30
            model: virtio
            name: enp1s0
        memory:
          guest: 24Gi
      networks:
      - multus:
          networkName: localnet-network
        name: enp1s0
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: sno1-rootdisk
        name: rootdisk
      - cloudInitNoCloud:
          networkData: |
            ethernets:
              enp1s0:
                addresses:
                  - 192.168.58.55
                gateway4: 192.168.58.1
            version: 2
        name: cloudinitdisk


