apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: sno1
  name: sno1
  namespace: sno-clusters
spec:
  runStrategy: RerunOnFailure
  dataVolumeTemplates:
    - kind: DataVolume
      metadata: 
        name: sno1-rootdisk
      spec:
        source:
          blank: {}
          size: 120Gi
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 120Gi
    - kind: DataVolume
      metadata:
        name: sno1-data
      spec:
        source:
          blank: {}
          size: 100Gi
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
    - kind: DataVolume
      metadata:
        name: sno1-cdrom
      spec:
        source:
          blank: {}
          size: 5Gi
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

  template:
    metadata:
      labels:
        kubevirt.io/domain: sno1
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 8
          sockets: 1
          threads: 2
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: data
            - disk:
                bus: scsi
              name: cdroom
          interfaces:
            - bridge: {}
              macAddress: de:ad:be:ff:20:30
              model: virtio
              name: enp1s0
        memory:
          guest: 24Gi
      networks:
        - multus:
            networkName: localnet-network
          name: enp1s0
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: sno1-rootdisk
          name: rootdisk
        - dataVolume:
            name: sno1-data
          name: data
        - dataVolume:
            name: sno1-cdroom
          name: cdroom


