apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: sno1
  name: sno1
  namespace: sno-clusters
spec:
  runStrategy: Halted
  dataVolumeTemplates:
    - kind: DataVolume
      metadata: 
        name: sno1-rootdisk
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: "true"
      spec:
        source:
          blank: {}
          size: 120Gi
        storage:
          resources:
            requests:
              storage: 120Gi
    - kind: DataVolume
      metadata:
        name: sno1-data
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: "true"
      spec:
        source:
          blank: {}
          size: 100Gi
        storage:
          resources:
            requests:
              storage: 100Gi
    - kind: DataVolume
      metadata:
        name: sno1-cdrom
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: "true"
      spec:
        source:
          http:
            url: http://192.168.58.15/iso/sno1.iso
          size: 5Gi
        storage:
          resources:
            requests:
              storage: 5Gi

  template:
    metadata:
      labels:
        kubevirt.io/domain: sno1
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 8
          sockets: 1
          threads: 2
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
              bootOrder: 2
            - disk:
                bus: virtio
              name: data
            - cdrom:
                bus: scsi
              name: cdroom
              bootOrder: 1
          interfaces:
            - bridge: {}
              macAddress: de:ad:be:ff:20:30
              model: virtio
              name: enp1s0
        memory:
          guest: 24Gi
      networks:
        - multus:
            networkName: localnet-network
          name: enp1s0
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: sno1-rootdisk
          name: rootdisk
        - dataVolume:
            name: sno1-data
          name: data
        - dataVolume:
            name: sno1-cdroom
          name: cdroom


