apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: master2
  name: master2
  namespace: vacm-hub2
spec:
  runStrategy: RerunOnFailure
  dataVolumeTemplates:
    - kind: DataVolume
      metadata:
        name: master2-rootdisk
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 120Gi
        storage:
          resources:
            requests:
              storage: 120Gi
    - kind: DataVolume
      metadata:
        name: master2-data
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
        storage:
          resources:
            requests:
              storage: 100Gi
    - kind: DataVolume
      metadata:
        name: master2-cdroom
      spec:
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
        storage:
          resources:
            requests:
              storage: 5Gi

  template:
    metadata:
      labels:
        kubevirt.io/domain: master2
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 8
          sockets: 1
          threads: 2
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: data
            - disk:
                bus: scsi
              name: cdroom
          interfaces:
            - bridge: { }
              macAddress: de:ad:be:ff:40:10
              model: virtio
              name: enp1s0
        memory:
          guest: 16Gi
      networks:
        - multus:
            networkName: localnet-network
          name: enp1s0
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: master2-rootdisk
          name: rootdisk
        - dataVolume:
            name: master2-data
          name: data
        - dataVolume:
            name: master2-cdroom
          name: cdroom

