apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: master3
  name: master3
  namespace: vacm-hub2
spec:
  runStrategy: RerunOnFailure
  dataVolumeTemplates:
    - kind: DataVolume
      metadata:
        name: master3-rootdisk
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: "true"
      spec:
        source:
          blank: {}
          size: 120Gi
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 120Gi
    - kind: DataVolume
      metadata:
        name: master3-data
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: "true"
      spec:
        source:
          blank: {}
          size: 100Gi
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Gi
    - kind: DataVolume
      metadata:
        name: master3-cdroom
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: "true"
      spec:
        source:
          blank: {}
          size: 5Gi
        pvc:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
  template:
    metadata:
      labels:
        kubevirt.io/domain: master3
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 8
          sockets: 1
          threads: 2
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: data
            - disk:
                bus: scsi
              name: cdroom
          interfaces:
            - bridge: { }
              macAddress: de:ad:be:ff:40:20
              model: virtio
              name: enp1s0
        memory:
          guest: 16Gi
      networks:
        - multus:
            networkName: localnet-network
          name: enp1s0
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: master3-rootdisk
          name: rootdisk
        - dataVolume:
            name: master3-data
          name: data
        - dataVolume:
            name: master3-cdroom
          name: cdroom

