apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: acm1-master1
  name: acm1-master1
  namespace: vacm1
spec:
  runStrategy: Halted
  dataVolumeTemplates:
    - kind: DataVolume
      metadata:
        name: master1-rootdisk
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: "true"
      spec:
        source:
          blank: {}
          size: 120Gi
        storage:
          resources:
            requests:
              storage: 120Gi
    - kind: DataVolume
      metadata:
        name: master1-data
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: "true"
      spec:
        source:
          blank: {}
          size: 100Gi
        storage:
          resources:
            requests:
              storage: 100Gi 
    - kind: DataVolume
      metadata:
        name: master1-cdrom
        annotations:
          cdi.kubevirt.io/storage.bind.immediate.requested: "true"
      spec:
        source:
          http:
            url: http://192.168.58.15/iso/vacm1.iso
        storage:
          resources:
            requests:
              storage: 5Gi 

  template:
    metadata:
      labels:
        kubevirt.io/domain: master1
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 10
          sockets: 1
          threads: 2
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
              bootOrder: 1
            - disk:
                bus: virtio
              name: data
            - cdrom:
                bus: scsi
              name: cdrom
              bootOrder: 2
          interfaces:
            - bridge: { }
              macAddress: de:ad:be:ff:20:00
              model: virtio
              name: enp1s0
        memory:
          guest: 40Gi
      networks:
        - multus:
            networkName: localnet-network
          name: enp1s0
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: master1-rootdisk
          name: rootdisk
        - dataVolume:
            name: master1-data
          name: data
        - dataVolume:
            name: master1-cdrom
          name: cdrom


